# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresarialMod1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco_cep', models.CharField(max_length=8)),
                ('risco_lograd', models.CharField(max_length=100)),
                ('risco_bairro', models.CharField(max_length=50)),
                ('risco_uf', models.CharField(max_length=50)),
                ('risco_municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
