# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copar_app', '0002_auto_20171123_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresarialQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco_cep', models.CharField(max_length=8)),
                ('area_predios', models.CharField(max_length=200)),
                ('valor_estoque', models.CharField(max_length=200)),
                ('valor_maquinas', models.CharField(max_length=200)),
                ('desc_vizinhanca', models.CharField(max_length=300)),
                ('quant_extintores', models.CharField(max_length=100)),
                ('desc_distrib_ext', models.CharField(max_length=200)),
                ('desc_hidrant', models.CharField(max_length=200)),
                ('cor_dutos', models.CharField(max_length=200)),
                ('duto_ferro_aco', models.CharField(max_length=200)),
                ('quant_lt_reserv_incend', models.CharField(max_length=100)),
                ('quant_agua_consum_local', models.CharField(max_length=100)),
                ('para_raio_mod', models.CharField(max_length=100)),
                ('brigada_incendio', models.CharField(max_length=100)),
                ('desc_material_protecao', models.CharField(max_length=100)),
                ('dist_bombeiros', models.CharField(max_length=100)),
                ('cameras_cftv', models.CharField(max_length=100)),
                ('onde_grava_img', models.CharField(max_length=200)),
                ('vigilancia', models.CharField(max_length=200)),
                ('empr_ext_monit', models.CharField(max_length=200)),
                ('aluguel_predio', models.CharField(max_length=100)),
                ('valor_aluguel', models.CharField(max_length=200)),
                ('somatorio_desp_fixa', models.CharField(max_length=200)),
                ('faturamento_mensal', models.CharField(max_length=200)),
                ('carga_luz_rua_emp', models.CharField(max_length=100)),
                ('quant_transformadores', models.CharField(max_length=200)),
                ('transf_carga_dist', models.CharField(max_length=200)),
                ('desc_geradores', models.CharField(max_length=200)),
                ('desc_inst_eletrica', models.CharField(max_length=200)),
                ('manutencao', models.CharField(max_length=100)),
                ('padrao_quadro_luz', models.CharField(max_length=100)),
                ('data_fund_emp', models.DateTimeField()),
                ('atividade_princ_cliente', models.CharField(max_length=500)),
                ('historico_acidente', models.CharField(max_length=500)),
                ('cob_ultimo_seguro', models.CharField(max_length=200)),
                ('seguro_negado', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='EmpresarialMod1',
        ),
    ]
