# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copar_app', '0004_auto_20171123_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresarialquest',
            name='cliente',
            field=models.CharField(default='adalto', max_length=200),
            preserve_default=False,
        ),
    ]
